#!/usr/bin/env python3
"""One-time data prep. Not a runtime dependency and not a build step for the viewer.

Run after editing data/states.json:  python3 prep.py

Does two things:
  1. Strips Inkscape/sodipodi cruft and hardcoded fills from us_raw.svg and inlines the
     result into index.html between the <!--SVG--> markers, so the page ships as one file
     plus two scripts and needs no fetch().
  2. Regenerates data/states.js from data/states.json. The JSON stays the canonical,
     hand-edited source of truth; the .js wrapper exists only so the page works when
     opened directly from disk (file:// blocks fetch, and a demo that needs a server is
     a demo that can fail in the room).
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
START, END = "<!--SVG-->", "<!--/SVG-->"


def clean_svg(raw):
    """Strip editor metadata and per-path fills; CSS owns colour from here on."""
    raw = re.sub(r"<(metadata|sodipodi:namedview|defs)\b.*?</\1>", "", raw, flags=re.S)
    raw = re.sub(r"<(sodipodi:namedview|metadata|defs)\b[^>]*/>", "", raw)
    raw = re.sub(r"\s(?:inkscape|sodipodi):[\w-]+\s*=\s*\"[^\"]*\"", "", raw)
    raw = re.sub(r"\sxmlns:(?:inkscape|sodipodi|dc|cc|rdf|svg)\s*=\s*\"[^\"]*\"", "", raw)
    # Per-path style carries fill:#f9f9f9, which would beat the status classes.
    raw = re.sub(r"\sstyle=\"[^\"]*\"", "", raw)
    raw = re.sub(r"<\?xml[^>]*\?>", "", raw)
    raw = re.sub(r"<!--.*?-->", "", raw, flags=re.S)
    m = re.search(r"<svg\b.*</svg>", raw, flags=re.S)
    if not m:
        sys.exit("prep: no <svg> element found in us_raw.svg")
    svg = m.group(0)
    # Drop fixed pixel dimensions so the map scales to its container.
    svg = re.sub(r'\s(?:height|width)="[^"]*"', "", svg, count=2)
    if not re.search(r"viewBox=", svg):
        svg = svg.replace("<svg", '<svg viewBox="0 0 1000 589"', 1)
    svg = svg.replace("<svg", '<svg id="usmap" role="img" aria-label="Map of US states by AI resilience law status"', 1)
    svg = re.sub(r"\n\s*\n+", "\n", svg)
    return svg


def main():
    with open(os.path.join(HERE, "us_raw.svg")) as fh:
        svg = clean_svg(fh.read())
    n_paths = svg.count("<path")
    if n_paths < 50:
        sys.exit("prep: expected 51 state paths, found %d — refusing to write a broken map" % n_paths)

    idx = os.path.join(HERE, "index.html")
    with open(idx) as fh:
        html = fh.read()
    i = html.find(START)
    if i == -1:
        sys.exit("prep: %s marker missing from index.html" % START)
    j = html.find(END)
    tail = html[j + len(END):] if j != -1 else html[i + len(START):]
    html = html[:i] + START + "\n" + svg + "\n" + END + tail
    with open(idx, "w") as fh:
        fh.write(html)

    with open(os.path.join(HERE, "data", "states.json")) as fh:
        data = json.load(fh)
    with open(os.path.join(HERE, "data", "states.js"), "w") as fh:
        fh.write("/* GENERATED by prep.py from states.json — do not edit by hand. */\n")
        fh.write("window.LAWMAP_DATA = ")
        json.dump(data, fh, ensure_ascii=False, separators=(",", ":"))
        fh.write(";\n")

    print("prep: inlined %d paths; wrote states.js (%d states, %d categories)"
          % (n_paths, len(data["states"]), len(data["categories"])))


if __name__ == "__main__":
    main()
